### ISSUE TITLE
Mensagem : '', valor hexadecimal 0x01, é um caractere inválido.

### ISSUE THREAD

**Issue by wikermoura** [OpenAC-Net/OpenAC.Net.NFSe#10]
A todos em primeiro lugar quero dar os parabéns por este projeto.

Mensagem : '', valor hexadecimal 0x01, é um caractere inválido.

Alguém poderia me ajudar por favor. Eu descompactei o projeto, e rodei o demo, coloco as configurações da cidade de Uberlândia,
e quando tento rodar, da esta mensagem. No meu projeto, quando gero o rps e mando enviar ele também da esta mensagem. Alguém já viu algo a respeito?

**Comment by rftd** [comment]
Geralmente este erro é  caractere especial

**Comment by rftd** [comment]
pelo visto tem algum erro ao gerar o xml do rps, vou colocar na lista para analise

**Comment by wikermoura** [comment]
A todos bom dia.

Descobri, o erro ocorre quando seleciono a cidade de Uberlândia, porém esta fixo no código exemplo a natureza da operação para outro provedor. No meu caso o correto é Dsf, então quando alterei no exemplo deu certo para gerar o XML.

Apesar que agora estou tendo o problema de erro ao efetuar a assinatura digital. Mas podem fechar este porque para este caso esta resolvido.

Muito obrigado
