### ISSUE TITLE
Erro ao efetuar assinatura digital.

### ISSUE THREAD

**Issue by wikermoura** [OpenAC-Net/OpenAC.Net.NFSe#11]
A todos boa tarde.

Pessoal, estou tendo este problema ao gerar o XML pelo DEMO, seleciono a prefeitura de Uberlândia-MG e recebo esta mensagem, o certificado digital é o da empresa prestadora. Tem algum norte onde posso buscar mais informações para este retorno?

**Comment by rftd** [comment]
Cara provedor DSF não tem ambiente de teste, então provavelmente ele está questionando o fato do certificado digital usada não ser de uma empresa prestadora cadastrada na prefeitura.

**Comment by wikermoura** [comment]
Opa, eu coloquei ambiente de homologação e o certificado é o da minha empresa que esta cadastrado na prefeitura, então vou colocar como produção para realizar o teste. Muito obrigado pelo retorno tão rapido. Você sabe de alguém que topa fazer um serviço de consultoria para implantar a emissão da nfse em meu sistema? To achando mais rapido encontrar alguém que já tenha a expertise para isso.

**Comment by wikermoura** [comment]
Não deu certo, eu coloquei o meu cnpj com o meu certificado, e ele da o erro na hora de assinar no XML. Esta mensagem já é um retorno do provedor ?

**Comment by wikermoura** [comment]
Boa noite, quando estou gerando o RPS recebo a mensagem de que erro ao efetuar a assinatura digital. Verifiquei no xml que esta sendo gerado o xml desta forma:
<?xml version="1.0" encoding="UTF-8"?>
-<ns1:ReqEnvioLoteRPS xsi:schemaLocation="http://localhost:8080/WsNFe2/lote http://localhost:8080/WsNFe2/xsd/ReqEnvioLoteRPS.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tipos="http://localhost:8080/WsNFe2/tp" xmlns:ns1="http://localhost:8080/WsNFe2/lote">
-<Cabecalho>
<CodCidade>5403</CodCidade>
<CPFCNPJRemetente>apagueiaquimas traz o cnpj do cliente</CPFCNPJRemetente>
<RazaoSocialRemetente>UDISYS CONSULTORIA E DESENVOLVIMENTO DE SISTEMAS</RazaoSocialRemetente>
<transacao/>
<dtInicio>2021-12-27</dtInicio>
<dtFim>2021-12-27</dtFim>
<QtdRPS>1</QtdRPS>
<ValorTotalServicos>10,00</ValorTotalServicos>
<ValorTotalDeducoes>0,00</ValorTotalDeducoes>
<Versao>1</Versao>
<MetodoEnvio>WS</MetodoEnvio>
</Cabecalho>
<Lote Id="lote:1">%NOTAS%</Lote>
</ns1:ReqEnvioLoteRPS>

O problema em sobrescrever as %NOTAS%. Alguém poderia por favor me ajudar, não estou encontrando onde estou falhando.

**Comment by wikermoura** [comment]
A todos, bom dia e feliz ano novo. Eu consegui assinar corretamente o xml alterando esta linha:
        protected override void AssinarEnviar(RetornoEnviar retornoWebservice)
        {
            //retornoWebservice.XmlEnvio = XmlSigning.AssinarXml(retornoWebservice.XmlEnvio, "ns1:ReqEnvioLoteRPS", "Lote", Certificado, true);
            retornoWebservice.XmlEnvio = XmlSigning.AssinarXml(retornoWebservice.XmlEnvio, "ns1:ReqEnvioLoteRPS", "", Certificado);
        }

que esta em ProviderDSF.cs, o que fiz foi remover o "Lote", será que alguma falha minha de configuração ou realmente não precisa do lote, pois esta assinando perfeitamente agora. Podem me ajudar por favor.
