### ISSUE TITLE
Nao é possivel informar a serie do certificado no projeto demo

### ISSUE THREAD

**Issue by transis2** [OpenAC-Net/OpenAC.Net.NFSe#116]
Como não abre a tela para seleção do certificado, não tem como informar ele no projeto demo.

![image](https://user-images.githubusercontent.com/4941173/186649113-499a7bcc-6ac6-4132-9287-a33f8dba801b.png)

**Comment by transis2** [comment]
Se digitar o numero de serie, apaga os campos caminho e senha

![image](https://user-images.githubusercontent.com/4941173/186649343-69443c60-6175-4bb4-8207-f6ee59ddc205.png)

**Comment by transis2** [comment]
Fiz uma alteracao para permitir informar o numero de serie, veja se tu concorda com o PR https://github.com/OpenAC-Net/OpenAC.Net.NFSe/issues/116

**Comment by rftd** [comment]
Este comportamento é o correto, não é para informar o certificado e o número de serie.
Sim um ou o outro.

**Comment by transis2** [comment]
Como fazer para informar agora com o .net 6 que não abre mais a selecao de certificado ?

**Comment by adrbarros** [comment]
![image](https://user-images.githubusercontent.com/15065213/186664601-7795b9b5-b26e-4cff-906d-4890883655f2.png)

![image](https://user-images.githubusercontent.com/15065213/186664959-27bbdc02-5612-433b-9c56-29d4012d16e8.png)

![image](https://user-images.githubusercontent.com/15065213/186665161-265acd02-8c1f-472b-8751-cdeec9d472ea.png)
Clique Duplo sobre o certificado

![image](https://user-images.githubusercontent.com/15065213/186665361-59b725b2-b349-406f-915b-647209890a61.png)
Pronto, ta ai o número

**Comment by rftd** [comment]
Tem como chamar a tela direto no app em .net 6, winforms tbm

**Comment by transis2** [comment]
@adrbarros Perfeito, eu fiz um PR para possibilitar digitar manualmente o numero de série enquanto não estava abrindo a tela para seleção do certificado.

**Comment by transis2** [comment]
> Pronto, ta ai o número. Pode ser uma solução para o momento.

@adrbarros Perfeito, eu fiz um PR https://github.com/OpenAC-Net/OpenAC.Net.NFSe/pull/119 (workaround) para possibilitar digitar manualmente o numero de série, enquanto não estava abrindo a tela para seleção do certificado.

No momento temos esse bug, que não permite executar o projeto demo.

**Comment by rftd** [comment]
@transis2 não tem bug algum, o que temos no .net framework é apenas uma conveniência, não e obrigação da Biblioteca mostra a tela de seleção de certificados.
Como disse basta copiar o código e colocar no demo ou no seu projeto que tu vai ter o mesmo efeito.

**Comment by rftd** [comment]
var store = new X509Store(StoreName.My, StoreLocation.CurrentUser);

                store.Open(OpenFlags.MaxAllowed | OpenFlags.ReadOnly);

                var certificates = store.Certificates.Find(X509FindType.FindByTimeValid, DateTime.Now, true)
                    .Find(X509FindType.FindByKeyUsage, X509KeyUsageFlags.DigitalSignature, false);

                X509Certificate2Collection certificadosSelecionados;
                certificadosSelecionados = X509Certificate2UI.SelectFromCollection(certificates, "Certificados Digitais",
                        "Selecione o Certificado Digital para uso no aplicativo", X509SelectionFlag.SingleSelection);

                var certificado = certificadosSelecionados.Count < 1 ? null : certificadosSelecionados[0];
                txtNumeroSerie.Text = certificado?.GetSerialNumberString() ?? string.Empty;

**Comment by transis2** [comment]
Não estou conseguindo colocar o número de serie.
Quando eu seleciono o certificado, ele limpa todos os campos.
![image](https://user-images.githubusercontent.com/4941173/187253422-e97c1845-bb6c-48bf-9771-56497a946a80.png)
