### ISSUE TITLE
Adicionar Piracicaba como município aceito

### ISSUE THREAD

**Issue by AlexandreBellas** [OpenAC-Net/OpenAC.Net.NFSe#146]
Boa tarde, pessoal!

Eu gostaria de verificar com vocês a possibilidade de adicionar Piracicaba como um município suportado pela biblioteca, visto que existe a implementação do provedor SIMPLISS e a cidade o usa.

Se for o caso, posso abrir um PR para incluir a cidade no arquivo [Municipios.nfse](https://github.com/OpenAC-Net/OpenAC.Net.NFSe/blob/main/src/OpenAC.Net.NFSe/Resources/Municipios.nfse)?

Fico no aguardo

**Comment by rftd** [comment]
basta fazer o PR.
