### ISSUE TITLE
Incluir Município pra uso da Biblioteca

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [OpenAC-Net/OpenAC.Net.NFSe#151]
Cidade Ilheus :
 Código IBGE: 2913606
UF: BA

Alguém poderia incluir esse município como aceiro, me informaram que já usaram a biblioteca pra Emissão em Lauro de Freitas BA, usando o provedor: Metropolis WWeb
Esse é a url do webservice da cidade: http://[ilheus.metropolisweb.com.br:9091/webservicenfse/nfse/services?wsdl](http://ilheus.metropolisweb.com.br:9091/webservicenfse/nfse/services?wsdl)

Alguém também tem algum exemplo de como implementar essa biblioteca via C#, estou com duvidas, tem uma parte que pede arquivos com cidades no executável demo, onde pego esses arquivos ?

**Comment by AlexandreBellas** [comment]
Como o Metropolis WWeb já é um provedor cadastrado na biblioteca, é bem tranquilo fazer o cadastro da cidade.

Recomendo você fazer um fork da biblioteca, adicionar a configuração desta cidade no arquivo [Municipios.nfse](https://github.com/OpenAC-Net/OpenAC.Net.NFSe/blob/main/src/OpenAC.Net.NFSe/Resources/Municipios.nfse), fazer um teste para ver se tudo rola certinho e abrir um Pull Request para o @rftd aceitar. ;)

**Comment by EdsonRodrigoBA** [comment]
Bom dia, seria isso?
https://github.com/OpenAC-Net/OpenAC.Net.NFSe/pull/152

**Comment by EdsonRodrigoBA** [comment]
ola eu fiz a mudança, como faço pra ser aprovado?
https://github.com/OpenAC-Net/OpenAC.Net.NFSe/pull/152/files
Esta correto? é so aguardar a aprovação ?

**Comment by AlexandreBellas** [comment]
Bom dia Edson,
seria isso mesmo. Agora é aguardar a aprovação da adição da cidade.

@rftd consegue avaliar o PR #152 quando possível?
