### ISSUE TITLE
PDF NFSE

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [OpenAC-Net/OpenAC.Net.NFSe#154]
Ao salvar o PDF da NFSE, fica com um nome encima de "DEMO".
Como faço pra remover esse nome?

**Comment by EdsonRodrigoBA** [comment]
Outro ponto tambem é que minha aliquota de IIS, é de 2% e no danfe fica 200,00%, como ajustar?

**Comment by leandrosantoslss** [comment]
Boa noite @EdsonRodrigoBA , use o [OpenAC.Net.NFSe.DANFSe.FastReport.OpenSource](https://github.com/OpenAC-Net/OpenAC.Net.NFSe/tree/main/src/OpenAC.Net.NFSe.DANFSe.FastReport.OpenSource) para gerar o PDF, é a DLL Open Source da FastReports
