### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by Dufayel** [OpenAC-Net/OpenAC.Net.NFSe#161]
Bom dia pessoal, tudo bem?

Existe alguma documentação de uso da biblioteca?
Caso não exista poderiam me passar um ponto de entrada para estudar o código?

**Comment by guidi** [comment]
Acho que a melhor forma de se ambientar é olhar o aplicativo de demonstração, ele fica em src/OpenAC.Net.NFSe.Demo

**Comment by Dufayel** [comment]
> Acho que a melhor forma de se ambientar é olhar o aplicativo de demonstração, ele fica em src/OpenAC.Net.NFSe.Demo

Show de bola, muito obrigado!
