### ISSUE TITLE
Erro no EnviarLoteRPS do Sigiss

### ISSUE THREAD

**Issue by Transis-Felipe** [OpenAC-Net/OpenAC.Net.NFSe#166]
Testei a geração do LoteRPS e deu erro 500.

![image](https://user-images.githubusercontent.com/4941173/217644353-a80b15dd-220b-48d1-940f-5eb4d52a26a5.png)

Então peguei o xml de exemplo que o provedor usa e está fora desse padrão que estamos usando.

![image](https://user-images.githubusercontent.com/4941173/217644758-44e99612-0cf5-462a-9c2a-39ba359a6bd6.png)

Posso alterar para o novo modelo ?

**Comment by rftd** [comment]
tem que checar se é no nessa cidade ou se o provedor mudou mesmo, tem vezes que é outro layout do mesmo provedor

**Comment by Transis-Felipe** [comment]
Certo, vou criar outra versão desse provedor, pois a cidade de Marilia-SP usa do modo antigo
