### ISSUE TITLE
The requested security protocol is not supported

### ISSUE THREAD

**Issue by Transis-Felipe** [OpenAC-Net/OpenAC.Net.NFSe#175]
Após a migração para o .net 7, os projetos em .net framework 4.6.2 não estão mais aceitando SSL3

![image](https://user-images.githubusercontent.com/4941173/218749841-c3850a58-407e-48e9-9a59-5d70a00ceee2.png)

System.NotSupportedException
  HResult=0x80131515
  Message=The requested security protocol is not supported.
  Source=System.Net.ServicePoint
  StackTrace:
   at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   at OpenAC.Net.NFSe.OpenNFSe.Enviar(Int32 lote, Boolean sincrono) in /_/src/OpenAC.Net.NFSe/OpenNFSe.cs:line 89

  This exception was originally thrown at this call stack:
    [External Code]
    OpenAC.Net.NFSe.OpenNFSe.Enviar(int, bool) in OpenNFSe.cs

**Comment by Transis-Felipe** [comment]
Posso retirar o ssl3 e deixar tudo como estava no netcore ?

![image](https://user-images.githubusercontent.com/4941173/218750288-2b6a0d18-7704-4e37-900e-f03a60434268.png)

**Comment by rftd** [comment]
pode remover eu acho que ninguém nessa altura do campeonato usa ssl3 ainda

**Comment by Transis-Felipe** [comment]
Feito no PR https://github.com/OpenAC-Net/OpenAC.Net.NFSe/pull/177
