### ISSUE TITLE
Provedor Americana

### ISSUE THREAD

**Issue by RenatoGuarilhaCMCorp** [OpenAC-Net/OpenAC.Net.NFSe#189]
Bom dia,

Em primeiro lugar parabéns aos colegas desenvolvedores pelo trabalho, e espero num futuro próximo contribuir com alguns outros provedores que precisei implementar.

Sou desenvolvedor da área fiscal, e implementamos internamente NFe e NFse, mas o volume de novas prefeituras nos próximos meses me fez decidir migrar para o Open AC.Net. Porque é open source e nativo em c sharp.

Na minha avaliação peguei por referência uma Nota fiscal da prefeitura de Angra dos Reis,  e percebi uma semelhança muito grande com o desenvolvido para a Prefeitura de Americana.

Em contato com a equipe de desenvolvimento da Tiplan (que é o provedor de Angra dos Reis) eu descobri que são eles que fazem da prefeitura de Americana.

Dito isso, devo implementar no meu fork o provedor Tiplan, que atende inclusive a prefeitura de Americana, os dados da cidade de Angra dos Reis. E os ajustes que julgar necessário ao atendimento ao ABRASF 2.03 utilizado por eles.

Assim que concluir eu faço um pull request para vocês.

Obrigado mais uma vez pelo excelente trabalho.

**Comment by rftd** [comment]
Se americana é Tiplam então basta renomar ele para Tiplan e usar nas duas cidades

**Comment by RenatoGuarilhaCMCorp** [comment]
Pensei em fazer isso, mas existe uma especificidade no provedor americana implementado que não faz sentido para a cidade de angra dos reis:


            /*
             * Americana mudou a lista de serviços municipais, agora deve-se informar o código NBS no ItemListaServico
             * e informar o CNAE no CodigoTributacaoMunicipio ou no CodigoCnae (não precisa informar os dois)
             */
            servico.AddChild(AdicionarTag(TipoCampo.Str, "", "ItemListaServico", 1, 5, Ocorrencia.Obrigatoria, nota.Servico.CodigoNbs));


Se altero aqui, posso parar Americana.


Mas pra mim essa linha não faz sentido algum, porque existe uma tag XML própria para receber o código NBS.


Renato Guarilha Gomes, PMP
Gerência CMFlex Fiscal | NFe | NFSe | Vendas
Av. Embaixador Abelardo Bueno, 1023
22775-039 . Barra da Tijuca . Rio de Janeiro . RJ
Telefone: 21 3575-9100
www.cmcorp.com.br<http://www.cmcorp.com.br/>
De: Rafael Teno Dias ***@***.***>
Enviada em: segunda-feira, 13 de março de 2023 09:20
Para: OpenAC-Net/OpenAC.Net.NFSe ***@***.***>
Cc: Renato Guarilha Gomes ***@***.***>; Author ***@***.***>
Assunto: Re: [OpenAC-Net/OpenAC.Net.NFSe] Provedor Americana (Issue #189)


Se americana é Tiplam então basta renomar ele para Tiplan e usar nas duas cidades

**Comment by rftd** [comment]
Como sempre erro de programador de passar regra de negocio para o componente, em vez de no sistema fazer a alteração jogou para o componente, basta fazer como deve ser feito e a pessoa que ajuste no sistema dela.
