### ISSUE TITLE
A solicitação HTTP não está autorizada no esquema de autenticação de cliente 'Anonymous'

### ISSUE THREAD

**Issue by transis2** [OpenAC-Net/OpenAC.Net.NFSe#19]
Oi Rafael,

Tu que respira webservices, saberia me dar um norte a respeito do que pode ser esse problema ?

![image](https://user-images.githubusercontent.com/4941173/150865220-c37e5ede-4cea-4c68-95a9-eccdd76859b5.png)

Provedor SystemPro

**Comment by rftd** [comment]
Precisa usar o certificado neste provedor ai pelo visto

**Comment by transis2** [comment]
É o certificado que a gente passa no Config, né ?

```
        Configuracoes.Certificados.CertificadoBytes = myBytesCertificadoA1
        Configuracoes.Certificados.Senha = m_SenhaCertificado
```

Eu estou passando o certificado e marquei em comentário para nem aceitar o inicializador deste provedor sem o certificado, mas o erro continua o mesmo.
        //public SystemProServiceClient(ProviderSystemPro provider, TipoUrl tipoUrl) : base(provider, tipoUrl)
        //{
        //}

**Comment by transis2** [comment]
Já estava com https

![image](https://user-images.githubusercontent.com/4941173/151024741-dc0e2df2-f8d4-4b1e-8d7e-4d4485f42765.png)

Tentei com http e o link nao existe

![image](https://user-images.githubusercontent.com/4941173/151024908-3737e2b8-951d-44ab-8e14-6dc1a5f2ceed.png)

**Comment by rftd** [comment]
na mensagem esta HTTP

**Comment by transis2** [comment]
Fiz esse teste com o SOAP UI e deu o mesmo retorno.

Isso te diz alguma coisa ?

![image](https://user-images.githubusercontent.com/4941173/151363740-f4f71a7a-2596-4717-bff8-34d48d5e1cb5.png)

**Comment by rftd** [comment]
Me manda este projeto do soapui que faço uns testes aqui.
Entra no discord é mais fácil conversar por lá fico o dia todo lá;

**Comment by transis2** [comment]
[Canela-soapui-project.zip](https://github.com/OpenAC-Net/OpenAC.Net.NFSe/files/7958787/Canela-soapui-project.zip)

**Comment by transis2** [comment]
Bom dia Rafael,

Será que tu poderia testar a comunicação com esse provedor usando o acbr ?
Pois este provedor fica recomendando o uso do acbr pra quem tem problema.

Eles se negam a prestar suporte, mas se no acbr estiver com problema também, quem sabe eles arrumem.

**Comment by rftd** [comment]
@transis2 entra no discord fazendo favor.

**Comment by rftd** [comment]
@transis2 favor testar com a ultima versão.

**Comment by MateusKernDigibyte** [comment]
Bom dia, eu enfrentei esse erro na Nota Curitibana, e para consertar esse aviso utilizei o construtor do ServiceClient que manda o certificado junto:

![image](https://user-images.githubusercontent.com/50238521/158165512-79ee3dc1-10fb-4d3c-b3a0-f7c67761aa26.png)

**Comment by MateusKernDigibyte** [comment]
> Bom dia, eu enfrentei esse erro na Nota Curitibana, e para consertar esse aviso utilizei o construtor do ServiceClient que manda o certificado junto:
> 
> ![image](https://user-images.githubusercontent.com/50238521/158165512-79ee3dc1-10fb-4d3c-b3a0-f7c67761aa26.png)

É por causa dessas configurações aqui que temos que usar o construtor que utiliza o certificado:
![image](https://user-images.githubusercontent.com/50238521/158166572-7cf7b6cc-5b36-40c1-8dce-9d6105dfc98a.png)

**Comment by transis2** [comment]
> 

![image](https://user-images.githubusercontent.com/4941173/158674805-023b30f2-89e8-4239-940c-bd45a4d9944f.png)

**Comment by transis2** [comment]
> @transis2 favor testar com a ultima versão.

![image](https://user-images.githubusercontent.com/4941173/158674861-7a85677a-d9a6-479f-9b9e-e2f47708ff0b.png)

**Comment by transis2** [comment]
> Bom dia, eu enfrentei esse erro na Nota Curitibana, e para consertar esse aviso utilizei o construtor do ServiceClient que manda o certificado junto:
> 
> ![image](https://user-images.githubusercontent.com/50238521/158165512-79ee3dc1-10fb-4d3c-b3a0-f7c67761aa26.png)

Obrigado pela dica, vou dar uma olhada nisso.

**Comment by transis2** [comment]
Tentei contato com a prefeitura por telefone e email sem sucesso.

O cliente vai ir pessoalmente lá pra ver se abre um canal de comunicação.

Eu atualizo aqui quando tiver progresso...

**Comment by transis2** [comment]
Progresso. Vou deixar registrado aqui o que precisa fazer para o SystemPro quando ocorrer acesso negado:

É preciso habilitar, no site da prefeitura, a emissão por webservice.

![image](https://user-images.githubusercontent.com/4941173/160177583-7edac48d-af3f-4c42-a067-dd56a8048389.png)

**Comment by rftd** [comment]
pelo visto o problema foi resolvido fechando a issue.

**Comment by transis2** [comment]
Vou deixar registrado para quem precisar: 

A série do RPS deve ser "RPI"
