### ISSUE TITLE
Consulta GINFES

### ISSUE THREAD

**Issue by andrealmei** [OpenAC-Net/OpenAC.Net.NFSe#20]
Boa tarde!!!

Alguém sabe me dizer o que pode estar errado?! Toda consulta em provedores GINFES está com esse erro de inscrição municipal, já tentei com outros CNPJS e inscrições e nada.
*Consulta NFSe por Período

![Capturar](https://user-images.githubusercontent.com/40307336/152368565-a2ad43a9-1f00-4ea6-9f90-bcba614fb3aa.PNG)

Obrigado!

**Comment by rftd** [comment]
Pelo que vi no código a inscrição é passada no XML, só posso pensar que seja algum erro do provedor.

**Comment by andrealmei** [comment]
Existe algum suporte desses provedores? Pois tenho buscado documentação e materiais sobre essas integrações mas não achei nada. Aparentemente é algo geral, certo?

**Comment by rftd** [comment]
Suporte é com prefeitura se ligar no provedor eles te ignoram.

**Comment by andrealmei** [comment]
Você também testou e nada, né?! Acho que não tem o que fazer! Obrigado!

**Comment by rftd** [comment]
Não tenho como testar, não tenho certificado e nem nenhum cliente que possa usar o provedor Ginfes, eu só teste a geração e se o provedor recebeu.
Geralmente o retorno vem de prestador não cadastrado ou algo do tipo
