### ISSUE TITLE
Não está funcionando o upload rest no provedor IPM v2

### ISSUE THREAD

**Issue by Transis-Pedro** [OpenAC-Net/OpenAC.Net.NFSe#219]
![image](https://user-images.githubusercontent.com/75954341/229296762-8a0ea0c9-4469-4d53-b6b4-71c9b120ca67.png)

Dados para simular:

![image](https://user-images.githubusercontent.com/75954341/229296814-c5331a79-be63-4476-8b3f-97306adbd391.png)

![image](https://user-images.githubusercontent.com/75954341/229296847-c86c4ae7-72d2-4fce-a7ac-29739c8d64d8.png)

![image](https://user-images.githubusercontent.com/75954341/229296911-657f26cf-4437-4211-ac00-0f4ed474f13f.png)

Consultar por periodo no ambiente de produção: Digitar qualquer numero de nota no input e crash.

No método antigo do rest HttpClient estava funcionando.

**Comment by rftd** [comment]
Mandei uma possível correção para este problema.
