### ISSUE TITLE
Crash no provedor IPM

### ISSUE THREAD

**Issue by Transis-Pedro** [OpenAC-Net/OpenAC.Net.NFSe#220]
![image](https://user-images.githubusercontent.com/75954341/229297069-cd98917e-7ace-4933-a1b8-81ca420037e5.png)

Dados para simular:

![image](https://user-images.githubusercontent.com/75954341/229297222-74c12c3c-4670-42a1-bd9c-2d19986f37a1.png)

![image](https://user-images.githubusercontent.com/75954341/229296847-c86c4ae7-72d2-4fce-a7ac-29739c8d64d8.png)

![image](https://user-images.githubusercontent.com/75954341/229297175-66957234-faf9-44d0-9547-5d6dce8bfab6.png)

Consultar Lote no ambiente de produção: Digitar qualquer numero de nota no input e crash.

No método antigo do rest estava funcionando.

**Comment by rftd** [comment]
Issue duplicado fechando.
