### ISSUE TITLE
É possível voltar a compilar o projeto em .net 4.5.2 ?

### ISSUE THREAD

**Issue by Transis-Felipe** [OpenAC-Net/OpenAC.Net.NFSe#223]
Meus projetos que não foram migrados para .net 4.6 por motivos de incompatibilidade não conseguem mais usar a biblioteca.

**Comment by rftd** [comment]
É possível, basta voltar a usar os webrequest, mas não pretendo fazer o mesmo visto que já faz quase 1 ano que o suporte a estes frameworks foram descontinuados pela M$.

**Comment by Transis-Felipe** [comment]
Entao quem precisar usar o teu componente e nao puder migrar para o .net 4.6 é recomendado a parar de usar o componente ?

**Comment by rftd** [comment]
Se você pensa assim, não tenho muito o que fazer, sabe de uma coisa acho melhor é fechar o projeto mesmo, boa sorte a todos.
