### ISSUE TITLE
Consulta NFSe Ginfes retornando erro

### ISSUE THREAD

**Issue by ThalisonSantos** [OpenAC-Net/OpenAC.Net.NFSe#23]
Ao consultar um lote retorna essa msg

`<ns3:ConsultarLoteRpsResposta xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" xmlns:ns4="http://www.ginfes.com.br/tipos_v03.xsd" xmlns:ns3="http://www.ginfes.com.br/servico_consultar_lote_rps_resposta_v03.xsd">
<ns4:ListaMensagemRetorno>
<ns4:MensagemRetorno>
<ns4:Codigo>0</ns4:Codigo>
<ns4:Mensagem>[result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements]</ns4:Mensagem>
<ns4:Correcao>0</ns4:Correcao>
</ns4:MensagemRetorno>
</ns4:ListaMensagemRetorno>
</ns3:ConsultarLoteRpsResposta>`

**Comment by rftd** [comment]
isso é erro do servidor, não tem muito o que fazer da nossa parte.

**Comment by ThalisonSantos** [comment]
o pior é que é somente em uma nota com esse erro, como o erro não claro não da pra saber o que é

**Comment by rftd** [comment]
Pelo erro no algoritmo do servidor deve estar usando uma lambda expression do tipo single e a lista que ele ta usando tem 2 coisas iguais ai da este erro ai.

**Comment by ThalisonSantos** [comment]
vou entrar em contato com eles e passar esse xml pra eles verificarem

**Comment by ThalisonSantos** [comment]
> @ThalisonSantos conseguiu resolver isso ?

nada, mandei um email pra eles aguardando resposta

**Comment by rftd** [comment]
complicado, vou manter a issue aberta até termos uma resposta deles.
