### ISSUE TITLE
System.TypeInitializationException: Ao alterar o webservice de uma cidade

### ISSUE THREAD

**Issue by Transis-Felipe** [OpenAC-Net/OpenAC.Net.NFSe#244]
Após alterar os webservices de uma cidade, ao entrar novamente no programa ele dá erro.

System.TypeInitializationException: 'The type initializer for 'OpenAC.Net.NFSe.Providers.ProviderManager' threw an exception.'

![image](https://user-images.githubusercontent.com/4941173/232120172-8261e5ed-6834-4d51-a619-97e81d3e5b70.png)

Passos para repetir o problema:
1) Entrar no gerenciador de cidades e alterar uma cidade qualquer
2) Salvar o arquivo
3) Colocar o arquivo atualizado na pasta resources do projeto
4) Recompilar o projeto
5) Ao executar o projeto demo, dá erro.

**Comment by rftd** [comment]
o erro ai pelo visto tu pegou um arquivo antigo e tentou usar no novo, não existe mais Betha2 por isso o erro.

**Comment by Transis-Felipe** [comment]
Pode ser

**Comment by rftd** [comment]
Agora tem o Campo Provedor e o Campo Versão.
