### ISSUE TITLE
Continua sem o arquivo do ginfes

### ISSUE THREAD

**Issue by Transis-Felipe** [OpenAC-Net/OpenAC.Net.NFSe#248]
Passos para reproduzir:
1) Fazer download do projeto como zip
![image](https://user-images.githubusercontent.com/4941173/232765717-8731003e-a20b-4adb-8142-a404b7f8b0e1.png)

2) Descompactar em alguma pasta
3) Rebuild Solution
4) Erro

![image](https://user-images.githubusercontent.com/4941173/232497722-ed727fe6-2d9d-448d-b846-c337d4607521.png)

**Comment by rftd** [comment]
![image](https://user-images.githubusercontent.com/299476/232498512-5962b7d9-a594-4991-8b31-fbba1d9a4a1e.png)
o arquivo se encontra na pasta.

**Comment by Transis-Felipe** [comment]
![image](https://user-images.githubusercontent.com/4941173/232768403-3bb6e66f-2a3d-4926-8d35-b0eed943c1fe.png)
