### ISSUE TITLE
Adição de tabela para listar provedores de NFS-e e suas cidades

### ISSUE THREAD

**Issue by fsbflavio** [OpenAC-Net/OpenAC.Net.NFSe#260]
Gostaria de solicitar a adição de uma tabela que liste os provedores de NFS-e e as cidades em que são utilizados. Essa tabela será útil para identificar os provedores populares em diferentes regiões e facilitar a escolha do provedor adequado para cada cidade.

Provedor: Nome do provedor de NFS-e.
Cidades: Lista de cidades onde o provedor é utilizado.
Agradeço a consideração.

**Comment by rftd** [comment]
Ja tem a lista de provedores no readme do site, agora sobre que cidades atende vai depender de cada 1 pois os provedores não fornecem esta informação.
Se quiser saber quais cidades estão cadastradas atualmente basta abrir o demo la tem o gerenciador de cidades.
