### ISSUE TITLE
Erro envio IISnet

### ISSUE THREAD

**Issue by joaospagno2023** [OpenAC-Net/OpenAC.Net.NFSe#262]
Ola amigos estou executando um envio para Issnet para unidade de ribeirao preto , porem ao enviar estou recebendo o erro 
O formato do valor "xmlns:nfd="http://www.issnetonline.com.br/webservice/nfd"/RecepcionarLoteRps" é inválido.
nao consegui achar o erro poderiam me ajudar

**Comment by adrianotrentim** [comment]
Nossa meu amigo, quanto tempo essa issue aberta..... já resolver o problema? Eu estou em RP, emitindo normal pra cá, se ainda estiver com problemas me avisa ai.
