### ISSUE TITLE
[ERRO]Arquivo de Schema nao Encontrado

### ISSUE THREAD

**Issue by dkraide** [OpenAC-Net/OpenAC.Net.NFSe#263]
Ola, estou tentando implantar o NFSe no meu projeto WEB, mas me deparei com esse possivel BUG.
Erro:
![image](https://github.com/OpenAC-Net/OpenAC.Net.NFSe/assets/43674712/9fc680ac-7db2-4531-a0a8-85a3b8946a7f)

Pasta com os Schemas: 
![image](https://github.com/OpenAC-Net/OpenAC.Net.NFSe/assets/43674712/56f16c69-f6ac-4c27-a234-cb578144a32f)

a pasta e os arquivos existem... Seria alguma limitacao para projeto WEB? to desenvolvendo com asp .net core 5

**Comment by glaucodiogo** [comment]
Estou com o mesmo problema tambem, ao tentar emitir nota para SP

**Comment by dkraide** [comment]
> Estou com o mesmo problema tambem, ao tentar emitir nota para SP

@glaucodiogo  eu achei o problema. A versao do github e do Nuget estao diferentes. no github ele procura o schema indo na pasta Schemas/Simpliss/1.0/nomearquivo.xsd enquanto no pacote Nuget ele procura o arquivo na pasta Schemas/Simpliss direto, sem a versao do simpliss. 
Solucao temporaria: copia os arquivos da pasta 1.0 direto pro Simpliss

**Comment by glaucodiogo** [comment]
Consegui chegar em uma solucao para emitir nota para SP, eu precisei criar a pasta Schemas/São Paulo no projeto web e deu certo. Obrigado @dkraide

**Comment by glaucodiogo** [comment]
@dkraide voce conseguiu emitir uma danfe em pdf ? precisou instalar algo ?
