### ISSUE TITLE
Após atualizar o nuget para OpenAC...

### ISSUE THREAD

**Issue by danilobreda** [OpenAC-Net/OpenAC.Net.NFSe#28]
Erro: "Provedor para esta cidade não implementado ou não especificado!"
Estou utilizando Marília/SP. SIGISS, eu mesmo implementei na época, qual motivo para esse erro?

**Comment by rftd** [comment]
Provavelmente faltando a cidade no xml de cidades

**Comment by danilobreda** [comment]
Faltou setar o Configuracoes.WebServices.CodigoMunicipio = codigoMunicipio;
