### ISSUE TITLE
Ajuda com "Erro ao processar o retorno"

### ISSUE THREAD

**Issue by TransisVanessa** [OpenAC-Net/OpenAC.Net.NFSe#300]
Olá pessoal!
Alguém poderia me ajudar com esse problema?
![image](https://github.com/user-attachments/assets/e1159c0c-2346-4643-8269-7217b5c308a4)

![image](https://github.com/user-attachments/assets/cbc70133-09c7-4a93-8269-11ebbc54dd6c)

Desde já eu agradeço.

**Comment by rftd** [comment]
Ta com erro ao processar o retorno do servidor, pelo visto não veio no formato esperado.
E pelo erro tem algo de errado na assinatura.

**Comment by TransisVanessa** [comment]
Oi, bom dia!
Está dando erro antes de enviar para prefeitura, já na validação do schema.
![image](https://github.com/user-attachments/assets/2acf05e8-d5f9-4154-b2fa-7b7d24535e45)
![image](https://github.com/user-attachments/assets/656f2d8c-d05d-448c-bffb-9911a7fb8a88)

**Comment by rftd** [comment]
Qual o provedor e a cidade ?

**Comment by rftd** [comment]
Eu acho que achei o erro, vou dar uma testada e mais tarde devo subir correção.

**Comment by rftd** [comment]
Mandei uma correção favor baixar e testar novamente.
