### ISSUE TITLE
Método "ElementAnyNs"

### ISSUE THREAD

**Issue by diegodariolli** [OpenAC-Net/OpenAC.Net.NFSe#305]
Boa tarde pessoal,

Estou com um problema aqui, todos os métodos "TratarRetornoEnvio" utilizam o método de tratamento de XML chamado "ElementAnyNs".
A primeira vista penso que esse método deve obter o primeiro nó no XML com aquele nome independente do nível em que ele esteja.
Se é pra funcionar assim, não está funcionando, todos os provedores que estou testando estão voltando null no retorno dessa função.
Poderiam ajudar por favor?

**Comment by rftd** [comment]
Ele não faz isso não, ele procura apenas nos filhos ignorando o namespace da tag.

**Comment by diegodariolli** [comment]
Entendi, então tem alguns provedores que estão com problema no retorno, estou testando vários que vamos precisar.
Percebi que não estava retornando a lista de erros, já corrigi o SimplISS 2.03.
Como estamos com muita pressa para implementar o componente devido a demanda de clientes, estou mexendo aqui e depois conversamos sobre as mudanças.
