### ISSUE TITLE
Mensagem : Versão de mensagem não reconhecida.

### ISSUE THREAD

**Issue by nonatosegundo** [OpenAC-Net/OpenAC.Net.NFSe#31]
Bom dia.

Fiz diversos testes com varias cidades ja implementadas na biblioteca, e todos apresenta essa mensagem.

Tentei identificar o que seria o problema e não consegui. Alguem saberia dizer o porque?

Isso é apresentado quando tento transmitir para qualquer cidade no demo.

Não achei nada sobre isso em nenhum local do git.

Outra duvida, temos algum discord ou grupo para tratar duvidas?

![image](https://user-images.githubusercontent.com/16769046/157424902-b8c7bd0f-d7ee-4f44-b393-50baa4be6041.png)

**Comment by rftd** [comment]
Qual o provedor que tu ta testando ?
Tem um passo a passo de como reproduzir este erro ?

**Comment by nonatosegundo** [comment]
> Qual o provedor que tu ta testando ? Tem um passo a passo de como reproduzir este erro ?

Tentei São Paulo, Belo Horizonte e Ginfes... todos da a mesma mensagem.

Para gerar o erro, no Demo, preenchi todos os dados selecionei certificado.

Percebi que a exceção é gerada no NFSeSOAP11ServiceClient.cs na linha 78, no create message nos 3 casos.

Estou usando a ultima versão do Visual Studio versão comunity

**Comment by rftd** [comment]
Cara deve ter erro ai então pois aqui não da este erro não, e eu uso a ultima versão do VS tbm.
Tanto que estou neste momento fazendo testes no Ginfes normalmente.

**Comment by rftd** [comment]
https://discord.com/invite/brdmJ7Yv6w

**Comment by nonatosegundo** [comment]
Bom dia @rftd 

Consegui resolver. O problema era com a versáo do SDK que eu tinha instalado em minha maquina.

Esta instalado a versão 5, e tudo esta funcionando na versão 6

Como sugestão, gostaria de pontuar a adição da versão do SDK no readme.md

Ah, fiz a criação de um novo provider IssFortaleza e estou realizando testes. Quando concluido, enviarei para vocês disponibilizarem para todos.

Obrigado.

**Comment by rftd** [comment]
Não a biblioteca não depende do SDk 6 do .Net.
Esta biblioteca tem como alvo o .Net 4.5.2 e o .Net Standard 2.0.
