### ISSUE TITLE
Na demonstração não é possível procurar o arquivo de municípios

### ISSUE THREAD

**Issue by RodrigoLuz** [OpenAC-Net/OpenAC.Net.NFSe#4]
O arquivo municipios.nfse não aparece na caixa de seleção
Em FormMain alterar o método LoadMunicipios para

        private void LoadMunicipios()
        {
            ExecuteSafe(() =>
            {
                var arquivo = Helpers.OpenFile("Arquivo de cidades NFSe (*.nfse)|*.nfse|Todos os arquivos|*.*", "Selecione o arquivo de cidades");
                if (arquivo.IsEmpty()) return;

                ProviderManager.Load(arquivo);
                txtArquivoCidades.Text = arquivo;
                LoadData();
            });
        }

**Comment by rftd** [comment]
Quando quiser enviar correção faça um fork e um pull request.
