### ISSUE TITLE
Aliquota ISS SimpliSS

### ISSUE THREAD

**Issue by marcosgerene** [OpenAC-Net/OpenAC.Net.NFSe#41]
Para o SimplISS em produção a aliquota do ISS pode ter até 4 casas decimais (como no meu caso).

https://github.com/OpenAC-Net/OpenAC.Net.NFSe/blob/b3c6efd425d8973b20456ab51d7fbda064902447/src/OpenAC.Net.NFSe/Providers/SimplISS/ProviderSimplISS.cs#L93

Devendo ficar
```
valores.AddChild(AdicionarTag(TipoCampo.De4, "", "Aliquota", 1, 15, Ocorrencia.MaiorQueZero, nota.Servico.Valores.Aliquota)); 
```

**Comment by rftd** [comment]
Faz um PR mala

**Comment by marcosgerene** [comment]
Pra eu fazer um PR preciso abrir o VS, testar... se eu só reporto o erro você tem que abrir o VS, testar... strategy, em grego...

**Comment by rftd** [comment]
administrador de bosta tu heim.
Já fiz a correção.

**Comment by marcosgerene** [comment]
s2
