### ISSUE TITLE
Nao está encontrando o arquivo com schema no SystemPro

### ISSUE THREAD

**Issue by transis2** [OpenAC-Net/OpenAC.Net.NFSe#45]
Fiz o PR #42 para ignorar o arquivo de schema, pois não consegui simular o problema na máquina de desenvolvimento.

O erro acontece somente na máquina de um cliente

**Comment by rftd** [comment]
Quando o erro so acontece no cliente significa erro no deployment, lembrando que o schema tem que esta dentro da pasta SystemPro e esta pasta dentro de uma pasta Schema, e no componente deve passa o path para a pasta schema que ele vai montar o resto do path para localizar o Schema

**Comment by transis2** [comment]
Ele está na pasta dos schemas

Em outros provedores que eu implementei deu certo, só nesse caso que não.

![image](https://user-images.githubusercontent.com/4941173/162271125-d75e98c0-e873-4b86-b765-6b10fb3fbbc1.png)
