### ISSUE TITLE
Não Obrigatoriedade campo Série - Layout São Paulo

### ISSUE THREAD

**Issue by edugolive** [OpenAC-Net/OpenAC.Net.NFSe#46]
Fazendo teste com layout de São Paulo, percebi um erro.
The 'SerieRPS' element is invalid - The value '' is invalid according to its datatype 'http://www.prefeitura.sp.gov.br/nfe/tipos:tpSerieRPS' - The actual length is less than the MinLength value.

O campo Série na documentação de São Paulo não tem o preenchimento obrigatório, e temos casos onde o Prestador não informa a Série.

![layout-sao-paulo-campo-serie](https://user-images.githubusercontent.com/4749790/161761079-c3ef35ab-69c3-4d7c-823e-c9d8f9c02b5b.png)

**Comment by edugolive** [comment]
Rafael, eu vi sua alteração.
Mas creio que ainda assim vai dar erro.
FIcou assim: "chaveRPS.AddChild(AdicionarTag(TipoCampo.Str, "", "SerieRPS", 1, 5, Ocorrencia.NaoObrigatoria, nota.IdentificacaoRps.Serie));"
Creio que deva passar o parâmetro "min" como '0' e não '1', pois senão vai cair na validação desse if :
"
if (!conteudoProcessado.IsEmpty() && conteudoProcessado.Length < min && alerta.IsEmpty() && conteudoProcessado.Length > 1)
                {
                    alerta = ErrMsgMenor;
                }
"
Porque o valor de Série passado será nulo ou '' e cairá nessa validação "conteudoProcessado.Length < min", gerando erro.

**Comment by rftd** [comment]
isso não é erro é um warning apenas

**Comment by edugolive** [comment]
Ah sim, verdade. vlw

**Comment by edugolive** [comment]
Nesse mesmo ProviderSaoPaulo.cs, no método GetHashRps, ele tenta usar o campo Série, se tiver nulo vai quebrar.
Precisa por um tratamento nesse caso "nota.IdentificacaoRps.Serie.PadRight(5, ' ')". 

string hash = nota.Prestador.InscricaoMunicipal.PadLeft(8, '0') +
                          nota.IdentificacaoRps.Serie.PadRight(5, ' ') +
                          nota.IdentificacaoRps.Numero.PadLeft(12, '0') +
                          nota.IdentificacaoRps.DataEmissao.Year.ToString().PadLeft(4, '0') +
                          nota.IdentificacaoRps.DataEmissao.Month.ToString().PadLeft(2, '0') +
                          nota.IdentificacaoRps.DataEmissao.Day.ToString().PadLeft(2, '0') +
                          tipoTributacao +
                          situacao +
                          issRetido +
                          Convert.ToInt32(nota.Servico.Valores.ValorServicos * 100).ToString().PadLeft(15, '0') +
                          Convert.ToInt32(nota.Servico.Valores.ValorDeducoes * 100).ToString().PadLeft(15, '0') +
                          nota.Servico.ItemListaServico.PadLeft(5, '0') +
                          indCpfCnpjTomador +
                          nota.Tomador.CpfCnpj?.PadLeft(14, '0');
