### ISSUE TITLE
Erro de arquivo de logo ao imprimir

### ISSUE THREAD

**Issue by lrossism** [OpenAC-Net/OpenAC.Net.NFSe#49]
Ao realizar testes de impressão do danfse, apresenta erro de arquivo de logo.
 No exemplo notei que só é passado o parâmetro com o nome do arquivo.
Como deve ser informado os arquivos de logo no componente para impressão?

**Comment by lrossism** [comment]
no programa demo apresenta o mesmo erro
FastReport.Utils.CompilerException: '(0,0): Error CS0006: Não foi possível encontrar o arquivo de metadados 'Microsoft.CSharp'

![image](https://user-images.githubusercontent.com/58528200/162432842-4d781b00-bf40-4620-8c2e-5666e2217b13.png)

**Comment by wsskakoal** [comment]
Salve irmão, aqui eu passo a logo como byte[] 
menciono no report do fastreport dessa forma:

            report.SetParameterValue("Logo", logoEmpresa);
            report.SetParameterValue("LogoPrefeitura", logoPrefeitura);

**Comment by rftd** [comment]
se usar o .net core tinha que passar os bytes da imagem se usar o .net full carrega a imagem

**Comment by lrossism** [comment]
sim, resolvi este problema... como uso uma biblioteca compartilhada em .net standard para o app em .net core e o desktop .net 45 nos testes entre um e outro gerava problema, então isolei o código no fonte para ficar em byte e o problema foi solucionado.
