### ISSUE TITLE
Prestador indo vazio

### ISSUE THREAD

**Issue by ThalisonSantos** [OpenAC-Net/OpenAC.Net.NFSe#6]
depois que atualizei do acbr para openAC ao enviar o rps o prestador esta indo vazio mesmo sendo informado no prestador padrão nas configurações.
[Enviar-28-env.zip](https://github.com/OpenAC-Net/OpenAC.Net.NFSe/files/7442725/Enviar-28-env.zip)

**Comment by rftd** [comment]
Correção enviado e pacote nuget atualizado.
