### ISSUE TITLE
Problema no controle Inputbox

### ISSUE THREAD

**Issue by transis2** [OpenAC-Net/OpenAC.Net.NFSe#65]
Se utilizar multiline no prompt, o conteudo fica acavalado em cima do textbox

```
string Texto = "Linha 1" + System.Environment.NewLine + "Linha 2" + System.Environment.NewLine + "Linha 3";
if (InputBox.Show("Numero Lote", Texto, ref numero).Equals(DialogResult.Cancel)) return;
```

![image](https://user-images.githubusercontent.com/4941173/164002866-bc587b82-9b87-47dc-b0e1-2bf70229e4c3.png)

**Comment by rftd** [comment]
Este controle ai é apenas uma implementação simples, nunca foi feito para ser algo grande é apenas para mostrar algo simples e pegar, nunca foi planejado para ser multiline.
